### ISSUE TITLE
ETA on support for 5.1

### ISSUE THREAD

**Issue by vsiles** [let-def/migrate-parsetree#125]
Hi !
Do you have any kind of timeline for supporting 5.1 ? Thanks !
As for today, `opam show` still mentions `ocaml < 5. 1`

**Comment by pitag-ha** [comment]
Hi @vsiles, thanks for reaching out! Which project do you need OMP for?

OMP is superseded by Ppxlib by now. We thought that everyone had moved to Ppxlib by now.

About the timeline: Instead of a timeline for supporting 5.1, we were thinking of a timeline for discussing the deprecation of OMP with the OCaml community. None of the two options is set in stone, yet.

**Comment by vsiles** [comment]
> Hi @vsiles, thanks for reaching out! Which project do you need OMP for?
> 
> OMP is superseded by Ppxlib by now. We thought that everyone had moved to Ppxlib by now.
> 
> About the timeline: Instead of a timeline for supporting 5.1, we were thinking of a timeline for discussing the deprecation of OMP with the OCaml community. None of the two options is set in stone, yet.

Hi !
Here at Meta we have a couple of projects that still use it like https://github.com/facebook/flow and https://github.com/facebook/hhvm/tree/master/hphp/hack

However we also use ppxlib. I was not aware of the deprecation discussions, so I'll check with my fellow devs if we could migrate everything to ppxlib and be done with it ;)

Thanks ! I'll keep you posted

**Comment by vsiles** [comment]
Thanks to my wonderful colleagues, we no longer need OMP, so we'll be supporting any option you choose ;)
Thanks again !
