### ISSUE TITLE
Are there size limits on the binary ast as produced by --dump-ast?

### ISSUE THREAD

**Issue by rleonid** [let-def/migrate-parsetree#39]
I'm running to a weird bug that is resolved by removing that argument and compiling from the generated source.

**Comment by ghost** [comment]
I think it's quite large, what error are you getting?

**Comment by rleonid** [comment]
The concrete error is
```
File "_none_", line 1:
Error: Unbound value Nativeint
Hint: Did you mean nativeint?
```
when compiling the branch in [this](https://github.com/rleonid/bau/pull/32) PR. For context I'm using a [ppx](https://github.com/rleonid/bigarray_fold_ppx) and cppo to [generate](https://github.com/rleonid/bau/pull/32/files#diff-745ffe65e8fbbf70bfccfb3c35e833d4R309) [mono|di]morphic higher level functions (ex. `fold_left`, `map` ...) for Bigarrays (`Array1.t`'s in the current work). I've manually compiled the code *successfully* without that flag against the generated [code](https://github.com/rleonid/bau/pull/32/files#diff-cf18282f9de281b5e8e843659625cf3d) (it is 47700 lines) that I grabbed with `-dsource` so something seems fishy.

Maybe this should be filed under dune but is there a way to have dune omit this flag and go the slower text route? I'm fine with special casing a custom pp'ing rule?

**Comment by ghost** [comment]
The error doesn't look right, it should be something like `Unbound constructor Nativeint` or `Unbound module Native`, but not `Unbound value` since it is syntactically not possible to write an identifier starting with a capital letter.

My guess is that the generated AST is wrong, however when pretty printed, the printer prints something that ends up being valid OCaml code.

`--dump-ast` is necessary, it is the default mode for ppx rewriters. It means the the output will be a marshaled `Parsetree.structure/signature` value rather than source code. This has two advantages:

- it should be faster since you don't do the parsing twice
- locations are preserved, so errors and backtraces point to the right place in the original code rather than somewhere in the generated code that the user cannot see

**Comment by rleonid** [comment]
You were [right](https://github.com/rleonid/bigarray_fold_ppx/commit/8f054dc6aa7129a562aa06d9b62cf4587f1166cc), I was initially deceived into thinking that the ppx was correct because it worked for many other kinds and then started breaking with `Nativeint`. Thank you.

**Comment by ghost** [comment]
No problem. One way to make it easier to debug such errors would be to extend the invariants checks that are performed by the compiler to also check identifiers:

https://github.com/ocaml/ocaml/blob/trunk/parsing/ast_invariants.mli

**Comment by rleonid** [comment]
Thanks again, that's super helpful. I did not know about them.
