### ISSUE TITLE
Start supporting 4.08 / trunk

### ISSUE THREAD

**Issue by hhugo** [let-def/migrate-parsetree#50]

**Comment by copy** [comment]
The first beta of 4.08 has just been released. 4.08 support would be helpful so that we can test libraries that depend on OMP.

**Comment by hhugo** [comment]
I started doing some work on this a while ago, I think @Armael looked at this as well. https://github.com/hhugo/ocaml-migrate-parsetree/tree/408

**Comment by let-def** [comment]
In https://github.com/ocaml-ppx/ocaml-migrate-parsetree/tree/master/src/compiler-functions, there is an implementation of a portable "error_of_exn"
It works slightly differently from other OMP functions as it tries to expose the same API for all versions, rather than exposing the same API as the compiler chosen by the PPX implementor.

For 4.08, it seems we will need to version more bits of Location module, and it might be the right time to revisit the implementation of `error_of_exn`. What do you use it for? Would you mind if we broke the API a bit in exchange of a more stable/regular API for future versions? (@diml)

**Comment by ghost** [comment]
`error_of_exn` is not exposed, it's only used in `migrate_parsetree_driver.ml` in order to encode exceptions as extension point. This is needed when the driver is used via the `-ppx` option so that it is `ocamlopt` that reports the error. Otherwise you get a message of the form `Error: preprocessor failed ...`.

**Comment by Armael** [comment]
So we had a look at this with @let-def two weeks ago, and unfortunately I didn't do much afterwards. So let me try to recall first what I remember and what we concluded. @let-def please correct me if I'm missing something.

Supporting 4.08 is more complicated than usual because in https://github.com/ocaml/ocaml/pull/1952 I changed the `Location.error` type. The definition of `Location.error`:
- is currently not snapshotted by omp 
- is used in the implementation of functions snapshotted by omp (eg `Ast_mapper.extension_of_error`) 
- should be made available to PPXs so that they can produce errors (and then typically use `Ast_mapper.extension_of_error` to generate a corresponding `ocaml.error` extension node).

So it seems we want to snapshot `Location.error`. 
- the first step would be to snapshot it for ocaml <= 4.07. We did that on a branch ( https://github.com/Armael/ocaml-migrate-parsetree/commits/pre-408-Loc-snapshotted ). Now I need to test that it doesn't break any opam package. I could do that by opening a dummy PR on opam-repository and look at the CI result there -- is there a better way?
- Next we would do the same for 4.08, and snapshot the new error type(s) and the relevant subset of utility functions
- I'm not sure what the status of the `error_of_exn` hack mentioned by @let-def above. Could we get rid of it if we snapshot `Location.error_of_exn` the normal way? And would it make sense to snapshot this function generally speaking?

Thoughts?

**Comment by avsm** [comment]
Dummy PR on opam-repo is fine for now - just mark the PR as a draft one so it can’t be merged (this is a new option in the create pr button)

**Comment by Armael** [comment]
Here's a report on my progress:

The branch https://github.com/Armael/ocaml-migrate-parsetree/commits/pre-408-Loc-snapshotted snapshots a subset of the Location module for versions of ocaml currently supported by omp (ie <= 4.07). The corresponding opam CI run is here: https://ci.ocamllabs.io/ocaml/opam-repository/pr/13536 .

I think the current snapshotted subset is satisfying enough, and we could go for that. AFAIR packages that are broken in the CI are either:
- reason-related, see https://github.com/facebook/reason/pull/2345 which should fix them
- not reasonable to support in omp as-is (see e.g mdx, which seems to reimplement some toplevel logic and already has to use cppo)
- ocamlformat; see https://github.com/ocaml-ppx/ocamlformat/issues/630#issuecomment-471323382 . We need to provide an API in omp to capture warnings, and implement it differently depending on the version of the compiler (by generalizing https://github.com/ocaml-ppx/ocaml-migrate-parsetree/tree/master/src/compiler-functions I guess).

The work of actually snapshotting 4.08 remains to be done (and I don't know how to do that).

Now, I won't have time (or energy) in the next few weeks to continue working on this, so someone else please pick up the torch :).

**Comment by Armael** [comment]
NB: I'd still be happy to *review* the 4.08 port if someone does it, as the one responsible for the new Location API in ocaml 4.08...

**Comment by ghost** [comment]
We just had a chat about this, @xclerc is going to look at finishing the support for 4.08

**Comment by ghost** [comment]
BTW, the Location module seems pretty annoying to snapshot. In particular the 4.08 one. For now, we are not going to snapshot it at all. It doesn't seem necessary to do to unblock 4.08. I expect that there will be a few breakages in other projects, but we can simply deal with those on a case by case basis.

**Comment by let-def** [comment]
@diml after making a few attempts at finding a solution to this problem, I share your view.

**Comment by Armael** [comment]
Could you give more details about the difficulties specific to 4.08?
I expected the subset that I snapshot in my branch for <=4.07 to also be doable in 4.08, but maybe I was overly optimistic?

**Comment by ghost** [comment]
There seem to be a lot of new code in the `Location` module in 4.08, in particular code that uses stdlib functions that are only available in 4.08. As a result, it is harder to backport this module.

Regarding the error stuf, given than `Location.error` values are never passed as it to the compiler, I suggest to simply provide them as normal library functions implemented from scratch in one of the other ppx library, that will be a lot less code to maintain.

**Comment by Armael** [comment]
> Regarding the error stuf, given than Location.error values are never passed as it to the compiler, I suggest to simply provide them as normal library functions implemented from scratch in one of the other ppx library, that will be a lot less code to maintain.

That sounds fine to me. I think the main reason why ppx writers have been using random functions in `Location` is simply because some API is needed to emit errors from PPX (more conveniently than producing an ast ocaml.error node). 
Providing such an API outside of the compiler sounds very fine to me.

Then there's the ocamlformat issue (need of an API to capture warnings) but that can be handled later.

**Comment by hhugo** [comment]
Ocamlformat can probably rely on conditional compilation to address the issue.

**Comment by let-def** [comment]
Sounds good to me.

**Comment by aantron** [comment]
Any word on the separate `Location` library? It seems to be needed for ppx_tools_versioned. If nobody is working on it, shall I create it?

**Comment by hhugo** [comment]
FYI, ocamlformat has been fixed for 4.08 https://github.com/ocaml-ppx/ocamlformat/pull/763

**Comment by xclerc** [comment]
See https://github.com/ocaml-ppx/ocaml-migrate-parsetree/pull/70

**Comment by hhugo** [comment]
#70 has been merged
