### ISSUE TITLE
[feature request] support migration of `types.mli`

### ISSUE THREAD

**Issue by ejgallego** [let-def/migrate-parsetree#52]
Dear OMP developers,

the `ppx_import` rewriter user the `types.mli` module from OCaml. Thus, in order to port it to OMP (https://github.com/ocaml-ppx/ppx_import/pull/27 ) it would be great if OMP would include this module in the supported set.

IMHO this module is not too big and could prove useful for other rewriters. I could develop a compat machinery for `ppx_import`, but IMHO it seems like pointless duplication as OMP already has all the required meta-support.

Thanks!

**Comment by EduardoRFS** [comment]
I didn't knew there was this request. As you pointed out to me, there is this:

https://github.com/EduardoRFS/ocaml-migrate-types/

Which is not exactly reliable yet, I'm not sure if it makes sense to incorporate it here, but if no one is against it, I can make the PR, I need to try using the migrate-parsetree generator tho, as I wrote my own because I didn't knew about it.

**Comment by ghost** [comment]
The scope of `ocaml-migrate-parsetree` is to provide parsetree migrations. `Types` is part of the typedtree, so it's out of the scope of `ocaml-migrate-parsetree`.
